version: '3'
services:
  web:
    build: .
    container_name: web
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=php
    volumes:
      - ./db:/var/lib/mysql